<a href="https://colab.research.google.com/github/manhduc07/Toan/blob/main/baitap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
V = np.zeros((6, 12))

In [ ]:
V[0, 11] = 1
V[1, 11] = -1
gamma = 0.9
p = 0.8
p_down = 0.2

In [ ]:
lock = [(0, 4), (0, 8),
        (1, 4), (1, 6), (1, 8),
        (2, 1), (2, 2), (2, 4), (2, 6), (2, 8),
        (3, 1), (3, 6), (3, 8),
        (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 8), (4, 9),
        (5, 4)]

In [ ]:
for i in lock:
  V[i] = -100

In [ ]:
for _ in V:
  print(_)

[   0.    0.    0.    0. -100.    0.    0.    0. -100.    0.    0.    1.]
[   0.    0.    0.    0. -100.    0. -100.    0. -100.    0.    0.   -1.]
[   0. -100. -100.    0. -100.    0. -100.    0. -100.    0.    0.    0.]
[   0. -100.    0.    0.    0.    0. -100.    0. -100.    0.    0.    0.]
[   0. -100. -100. -100. -100. -100. -100.    0. -100. -100.    0.    0.]
[   0.    0.    0.    0. -100.    0.    0.    0.    0.    0.    0.    0.]


In [ ]:
def canMove(x, y, V, block_moves):
  up       = (x-1, y)
  down     = (x+1, y)
  left     = (x, y-1)
  right    = (x, y+1)
  moves    = [up, down, left, right]
  canMoves = []
  for move in moves:
      move_x, move_y = move
      if 0 <= move_x < V.shape[0] and 0 <= move_y < V.shape[1]:
            if move not in block_moves:
              canMoves.append(move)
  return canMoves

In [ ]:
def allMoves(V, block_moves):
  results = []
  for i in range(V.shape[0]):
    for j in range(V.shape[1]):
      obj = {(i, j): canMove(i, j, V, block_moves)}
      results.append(obj)
  return results;

In [ ]:
def addValue(value):
    allVal = []
    for val in value:
        allVal.append(val)
    return allVal

In [ ]:
def updateValue(value, gamma, V, p_down):
    listValue = addValue(value)
    maxValue = 0
    if len(value) > 1:
        sumVal = len(value) - 1
    else:
        sumVal = len(value)
    result = []
    for i in range(len(listValue)):
        sum = 0
        x_i, y_i = listValue[i]
        for j in range(len(listValue)):
            x_j, y_j = listValue[j]
            if j == i:
                sum += 0.8 * gamma * V[x_i][y_i]
            else:
                sum += (p_down / sumVal) * gamma * V[x_j][y_j]
        result.append(sum)
    maxValue = max(result)
    return maxValue

In [ ]:
moves = allMoves(V, lock)

In [ ]:
import pandas as pd

for __ in range(20):
  for i in moves:
    for _ in i:
      if(_ == (0,11) or _ == (1,11) or _ in lock):
         continue
      value = i[_]
      V[_] = updateValue(value, gamma, V, p_down)
  print(f'lan {__}')
  display(pd.DataFrame(V))

lan 0


0      1      2      3      4      5      6    7      8      9         10  \
0  0.0    0.0    0.0    0.0 -100.0    0.0    0.0  0.0 -100.0    0.0  0.720000   
1  0.0    0.0    0.0    0.0 -100.0    0.0 -100.0  0.0 -100.0    0.0  0.458400   
2  0.0 -100.0 -100.0    0.0 -100.0    0.0 -100.0  0.0 -100.0    0.0  0.330048   
3  0.0 -100.0    0.0    0.0    0.0    0.0 -100.0  0.0 -100.0    0.0  0.237635   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0  0.0 -100.0 -100.0  0.171097   
5  0.0    0.0    0.0    0.0 -100.0    0.0    0.0  0.0    0.0    0.0  0.123190   

         11  
0  1.000000  
1 -1.000000  
2  0.147635  
3  0.184384  
4  0.148155  
5  0.128846

lan 1


0      1      2      3      4      5      6    7      8           9   \
0  0.0    0.0    0.0    0.0 -100.0    0.0    0.0  0.0 -100.0    0.518400   
1  0.0    0.0    0.0    0.0 -100.0    0.0 -100.0  0.0 -100.0    0.414504   
2  0.0 -100.0 -100.0    0.0 -100.0    0.0 -100.0  0.0 -100.0    0.328147   
3  0.0 -100.0    0.0    0.0    0.0    0.0 -100.0  0.0 -100.0    0.279040   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0  0.0 -100.0 -100.000000   
5  0.0    0.0    0.0    0.0 -100.0    0.0    0.0  0.0    0.0    0.088697   

         10        11  
0  0.807912  1.000000  
1  0.566370 -1.000000  
2  0.450591  0.251020  
3  0.362497  0.296924  
4  0.285419  0.251069  
5  0.225080  0.221284

lan 2


0      1      2      3      4      5      6    7           8           9   \
0  0.0    0.0    0.0    0.0 -100.0    0.0    0.0  0.0 -100.000000    0.656307   
1  0.0    0.0    0.0    0.0 -100.0    0.0 -100.0  0.0 -100.000000    0.553048   
2  0.0 -100.0 -100.0    0.0 -100.0    0.0 -100.0  0.0 -100.000000    0.463861   
3  0.0 -100.0    0.0    0.0    0.0    0.0 -100.0  0.0 -100.000000    0.399230   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0  0.0 -100.000000 -100.000000   
5  0.0    0.0    0.0    0.0 -100.0    0.0    0.0  0.0    0.063862    0.173553   

         10        11  
0  0.830041  1.000000  
1  0.597848 -1.000000  
2  0.495093  0.293190  
3  0.415361  0.348043  
4  0.341914  0.301279  
5  0.281713  0.267629

lan 3


0      1      2      3      4      5      6        7           8   \
0  0.0    0.0    0.0    0.0 -100.0    0.0    0.0  0.00000 -100.000000   
1  0.0    0.0    0.0    0.0 -100.0    0.0 -100.0  0.00000 -100.000000   
2  0.0 -100.0 -100.0    0.0 -100.0    0.0 -100.0  0.00000 -100.000000   
3  0.0 -100.0    0.0    0.0    0.0    0.0 -100.0  0.00000 -100.000000   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0  0.00000 -100.000000   
5  0.0    0.0    0.0    0.0 -100.0    0.0    0.0  0.04598    0.133235   

           9         10        11  
0    0.697178  0.836552  1.000000  
1    0.597522  0.607875 -1.000000  
2    0.510705  0.510825  0.309118  
3    0.442473  0.435740  0.368668  
4 -100.000000  0.366202  0.322486  
5    0.226816  0.308165  0.287660

lan 4


0      1      2      3      4      5           6         7           8   \
0  0.0    0.0    0.0    0.0 -100.0    0.0    0.000000  0.000000 -100.000000   
1  0.0    0.0    0.0    0.0 -100.0    0.0 -100.000000  0.000000 -100.000000   
2  0.0 -100.0 -100.0    0.0 -100.0    0.0 -100.000000  0.000000 -100.000000   
3  0.0 -100.0    0.0    0.0    0.0    0.0 -100.000000  0.000000 -100.000000   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.000000  0.033106 -100.000000   
5  0.0    0.0    0.0    0.0 -100.0    0.0    0.033106  0.101888    0.181647   

           9         10        11  
0    0.709872  0.838597  1.000000  
1    0.611780  0.611146 -1.000000  
2    0.526278  0.516293  0.314911  
3    0.457353  0.443265  0.376516  
4 -100.000000  0.375909  0.330813  
5    0.254576  0.319456  0.295687

lan 5


0      1      2      3      4           5          6         7   \
0  0.0    0.0    0.0    0.0 -100.0    0.000000    0.00000  0.000000   
1  0.0    0.0    0.0    0.0 -100.0    0.000000 -100.00000  0.000000   
2  0.0 -100.0 -100.0    0.0 -100.0    0.000000 -100.00000  0.000000   
3  0.0 -100.0    0.0    0.0    0.0    0.000000 -100.00000  0.023836   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.000000 -100.00000  0.077650   
5  0.0    0.0    0.0    0.0 -100.0    0.023836    0.07765  0.144763   

           8           9         10        11  
0 -100.000000    0.713910  0.839255  1.000000  
1 -100.000000    0.616384  0.612224 -1.000000  
2 -100.000000    0.531424  0.518178  0.316974  
3 -100.000000    0.462413  0.445978  0.379405  
4 -100.000000 -100.000000  0.379628  0.334091  
5    0.209352    0.267692  0.324037  0.298872

lan 6


0      1      2      3      4           5           6         7   \
0  0.0    0.0    0.0    0.0 -100.0    0.000000    0.000000  0.000000   
1  0.0    0.0    0.0    0.0 -100.0    0.000000 -100.000000  0.000000   
2  0.0 -100.0 -100.0    0.0 -100.0    0.000000 -100.000000  0.017162   
3  0.0 -100.0    0.0    0.0    0.0    0.000000 -100.000000  0.058997   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.000000 -100.000000  0.114849   
5  0.0    0.0    0.0    0.0 -100.0    0.055908    0.114293  0.171356   

           8           9         10        11  
0 -100.000000    0.715213  0.839469  1.000000  
1 -100.000000    0.617882  0.612581 -1.000000  
2 -100.000000    0.533128  0.518823  0.317699  
3 -100.000000    0.464128  0.446943  0.380460  
4 -100.000000 -100.000000  0.381030  0.335482  
5    0.223582    0.273551  0.325860  0.300201

lan 7


0      1      2      3      4           5           6         7   \
0  0.0    0.0    0.0    0.0 -100.0    0.000000    0.000000  0.000000   
1  0.0    0.0    0.0    0.0 -100.0    0.000000 -100.000000  0.012357   
2  0.0 -100.0 -100.0    0.0 -100.0    0.000000 -100.000000  0.044702   
3  0.0 -100.0    0.0    0.0    0.0    0.000000 -100.000000  0.090737   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.000000 -100.000000  0.139709   
5  0.0    0.0    0.0    0.0 -100.0    0.082291    0.138189  0.185990   

           8           9         10        11  
0 -100.000000    0.715637  0.839540  1.000000  
1 -100.000000    0.618372  0.612700 -1.000000  
2 -100.000000    0.533694  0.519044  0.317953  
3 -100.000000    0.464709  0.447284  0.380854  
4 -100.000000 -100.000000  0.381565  0.336022  
5    0.230435    0.276097  0.326594  0.300723

lan 8


0      1      2      3      4           5           6         7   \
0  0.0    0.0    0.0    0.0 -100.0    0.000000    0.000000  0.008897   
1  0.0    0.0    0.0    0.0 -100.0    0.000000 -100.000000  0.033787   
2  0.0 -100.0 -100.0    0.0 -100.0    0.000000 -100.000000  0.071413   
3  0.0 -100.0    0.0    0.0    0.0    0.000000 -100.000000  0.113445   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.000000 -100.000000  0.154333   
5  0.0    0.0    0.0    0.0 -100.0    0.099496    0.151822  0.193467   

           8           9         10        11  
0 -100.000000    0.715776  0.839563  1.000000  
1 -100.000000    0.618534  0.612740 -1.000000  
2 -100.000000    0.533882  0.519120  0.318043  
3 -100.000000    0.464906  0.447406  0.380998  
4 -100.000000 -100.000000  0.381768  0.336228  
5    0.233614    0.277198  0.326886  0.300923

lan 9


0      1      2      3      4           5           6         7   \
0  0.0    0.0    0.0    0.0 -100.0    0.000000    0.006406  0.025480   
1  0.0    0.0    0.0    0.0 -100.0    0.000000 -100.000000  0.056003   
2  0.0 -100.0 -100.0    0.0 -100.0    0.000000 -100.000000  0.091761   
3  0.0 -100.0    0.0    0.0    0.0    0.000000 -100.000000  0.127637   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.000000 -100.000000  0.162271   
5  0.0    0.0    0.0    0.0 -100.0    0.109312    0.158972  0.197114   

           8           9         10        11  
0 -100.000000    0.715821  0.839571  1.000000  
1 -100.000000    0.618587  0.612753 -1.000000  
2 -100.000000    0.533945  0.519146  0.318075  
3 -100.000000    0.464974  0.447449  0.381051  
4 -100.000000 -100.000000  0.381844  0.336305  
5    0.235063    0.277669  0.327001  0.301000

lan 10


0      1      2      3      4           5           6         7   \
0  0.0    0.0    0.0    0.0 -100.0    0.004612    0.019176  0.043774   
1  0.0    0.0    0.0    0.0 -100.0    0.003321 -100.000000  0.073947   
2  0.0 -100.0 -100.0    0.0 -100.0    0.002391 -100.000000  0.105209   
3  0.0 -100.0    0.0    0.0    0.0    0.001721 -100.000000  0.135773   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.000000 -100.000000  0.166361   
5  0.0    0.0    0.0    0.0 -100.0    0.114460    0.162525  0.198845   

           8           9         10        11  
0 -100.000000    0.715836  0.839573  1.000000  
1 -100.000000    0.618605  0.612758 -1.000000  
2 -100.000000    0.533966  0.519155  0.318086  
3 -100.000000    0.464997  0.447465  0.381070  
4 -100.000000 -100.000000  0.381872  0.336334  
5    0.235714    0.277869  0.327046  0.301029

lan 11


0      1      2      3           4           5           6         7   \
0  0.0    0.0    0.0    0.0 -100.000000    0.014404    0.034110  0.059382   
1  0.0    0.0    0.0    0.0 -100.000000    0.010801 -100.000000  0.086439   
2  0.0 -100.0 -100.0    0.0 -100.000000    0.008087 -100.000000  0.113315   
3  0.0 -100.0    0.0    0.0    0.001239    0.006046 -100.000000  0.140177   
4  0.0 -100.0 -100.0 -100.0 -100.000000 -100.000000 -100.000000  0.168400   
5  0.0    0.0    0.0    0.0 -100.000000    0.117018    0.164232  0.199651   

           8           9         10        11  
0 -100.000000    0.715842  0.839574  1.000000  
1 -100.000000    0.618611  0.612759 -1.000000  
2 -100.000000    0.533974  0.519158  0.318090  
3 -100.000000    0.465005  0.447471  0.381077  
4 -100.000000 -100.000000  0.381883  0.336345  
5    0.236003    0.277954  0.327064  0.301040

lan 12


0      1      2           3           4           5           6   \
0  0.0    0.0    0.0    0.000000 -100.000000    0.026503    0.047525   
1  0.0    0.0    0.0    0.000000 -100.000000    0.020538 -100.000000   
2  0.0 -100.0 -100.0    0.000000 -100.000000    0.015876 -100.000000   
3  0.0 -100.0    0.0    0.000892    0.004513    0.012243 -100.000000   
4  0.0 -100.0 -100.0 -100.000000 -100.000000 -100.000000 -100.000000   
5  0.0    0.0    0.0    0.000000 -100.000000    0.118247    0.165033   

         7          8           9         10        11  
0  0.070791 -100.00000    0.715843  0.839574  1.000000  
1  0.094329 -100.00000    0.618613  0.612760 -1.000000  
2  0.117907 -100.00000    0.533976  0.519159  0.318092  
3  0.142471 -100.00000    0.465007  0.447473  0.381080  
4  0.169393 -100.00000 -100.000000  0.381887  0.336350  
5  0.200020    0.23613    0.277990  0.327072  0.301045

lan 13


0      1           2           3           4           5           6   \
0  0.0    0.0    0.000000    0.000000 -100.000000    0.037915    0.057794   
1  0.0    0.0    0.000000    0.000000 -100.000000    0.030157 -100.000000   
2  0.0 -100.0 -100.000000    0.000643 -100.000000    0.023916 -100.000000   
3  0.0 -100.0    0.000643    0.003365    0.009421    0.018916 -100.000000   
4  0.0 -100.0 -100.000000 -100.000000 -100.000000 -100.000000 -100.000000   
5  0.0    0.0    0.000000    0.000000 -100.000000    0.118824    0.165403   

         7           8           9         10        11  
0  0.078320 -100.000000    0.715844  0.839574  1.000000  
1  0.098990 -100.000000    0.618614  0.612760 -1.000000  
2  0.120398 -100.000000    0.533977  0.519160  0.318092  
3  0.143635 -100.000000    0.465008  0.447473  0.381081  
4  0.169869 -100.000000 -100.000000  0.381889  0.336351  
5  0.200188    0.236187    0.278005  0.327074  0.301046

lan 14


0      1           2           3          4           5           6   \
0  0.0    0.0    0.000000    0.000000 -100.00000    0.047040    0.064858   
1  0.0    0.0    0.000000    0.000463 -100.00000    0.038174 -100.000000   
2  0.0 -100.0 -100.000000    0.002506 -100.00000    0.030890 -100.000000   
3  0.0 -100.0    0.002423    0.007227    0.01492    0.024926 -100.000000   
4  0.0 -100.0 -100.000000 -100.000000 -100.00000 -100.000000 -100.000000   
5  0.0    0.0    0.000000    0.000000 -100.00000    0.119090    0.165572   

         7           8           9         10        11  
0  0.082947 -100.000000    0.715844  0.839574  1.000000  
1  0.101617 -100.000000    0.618614  0.612760 -1.000000  
2  0.121708 -100.000000    0.533977  0.519160  0.318092  
3  0.144213 -100.000000    0.465009  0.447474  0.381081  
4  0.170094 -100.000000 -100.000000  0.381889  0.336352  
5  0.200264    0.236211    0.278012  0.327076  0.301047

lan 15


0      1           2           3           4           5           6   \
0  0.0    0.0    0.000000    0.000333 -100.000000    0.053569    0.069365   
1  0.0    0.0    0.000333    0.001865 -100.000000    0.044130 -100.000000   
2  0.0 -100.0 -100.000000    0.005539 -100.000000    0.036260 -100.000000   
3  0.0 -100.0    0.005203    0.011709    0.020055    0.029717 -100.000000   
4  0.0 -100.0 -100.000000 -100.000000 -100.000000 -100.000000 -100.000000   
5  0.0    0.0    0.000000    0.000000 -100.000000    0.119212    0.165648   

         7           8           9         10        11  
0  0.085650 -100.000000    0.715844  0.839574  1.000000  
1  0.103047 -100.000000    0.618614  0.612760 -1.000000  
2  0.122382 -100.000000    0.533977  0.519160  0.318092  
3  0.144496 -100.000000    0.465009  0.447474  0.381081  
4  0.170200 -100.000000 -100.000000  0.381890  0.336352  
5  0.200298    0.236222    0.278014  0.327076  0.301047

lan 16


0          1           2           3           4           5           6   \
0  0.0    0.00000    0.000270    0.001391 -100.000000    0.057886    0.072087   
1  0.0    0.00024    0.001388    0.004238 -100.000000    0.048205 -100.000000   
2  0.0 -100.00000 -100.000000    0.009193 -100.000000    0.040056 -100.000000   
3  0.0 -100.00000    0.008431    0.016025    0.024281    0.033211 -100.000000   
4  0.0 -100.00000 -100.000000 -100.000000 -100.000000 -100.000000 -100.000000   
5  0.0    0.00000    0.000000    0.000000 -100.000000    0.119267    0.165683   

         7           8           9         10        11  
0  0.087169 -100.000000    0.715844  0.839574  1.000000  
1  0.103805 -100.000000    0.618614  0.612760 -1.000000  
2  0.122722 -100.000000    0.533977  0.519160  0.318092  
3  0.144634 -100.000000    0.465009  0.447474  0.381081  
4  0.170249 -100.000000 -100.000000  0.381890  0.336352  
5  0.200314    0.236227    0.278016  0.327076  0.301047

lan 17


0           1           2           3           4           5   \
0  0.000000    0.000216    0.001146    0.003258 -100.000000    0.060580   
1  0.000173    0.001035    0.003248    0.007205 -100.000000    0.050828   
2  0.000124 -100.000000 -100.000000    0.012835 -100.000000    0.042574   
3  0.000090 -100.000000    0.011538    0.019676    0.027454    0.035595   
4  0.000064 -100.000000 -100.000000 -100.000000 -100.000000 -100.000000   
5  0.000046    0.000033    0.000024    0.000017 -100.000000    0.119292   

           6         7           8           9         10        11  
0    0.073666  0.088000 -100.000000    0.715844  0.839574  1.000000  
1 -100.000000  0.104200 -100.000000    0.618614  0.612760 -1.000000  
2 -100.000000  0.122892 -100.000000    0.533977  0.519160  0.318092  
3 -100.000000  0.144700 -100.000000    0.465009  0.447474  0.381081  
4 -100.000000  0.170272 -100.000000 -100.000000  0.381890  0.336352  
5    0.165698  0.200321    0.236229    0.278016  0.327076  0.301047

lan 18


0           1           2           3           4           5   \
0  0.000186    0.000935    0.002722    0.005677 -100.000000    0.062189   
1  0.000773    0.002492    0.005657    0.010261 -100.000000    0.052439   
2  0.000573 -100.000000 -100.000000    0.016014 -100.000000    0.044163   
3  0.000424 -100.000000    0.014167    0.022483    0.029675    0.037139   
4  0.000314 -100.000000 -100.000000 -100.000000 -100.000000 -100.000000   
5  0.000232    0.000171    0.000126    0.000091 -100.000000    0.119303   

           6         7          8           9         10        11  
0    0.074554  0.088444 -100.00000    0.715844  0.839574  1.000000  
1 -100.000000  0.104402 -100.00000    0.618614  0.612760 -1.000000  
2 -100.000000  0.122976 -100.00000    0.533977  0.519160  0.318092  
3 -100.000000  0.144731 -100.00000    0.465009  0.447474  0.381081  
4 -100.000000  0.170283 -100.00000 -100.000000  0.381890  0.336352  
5    0.165705  0.200324    0.23623    0.278016  0.327076  0.301047

lan 19


0           1           2           3           4           5   \
0  0.000812    0.002257    0.004800    0.008252 -100.000000    0.063118   
1  0.001919    0.004449    0.008221    0.013012 -100.000000    0.053394   
2  0.001458 -100.000000 -100.000000    0.018530 -100.000000    0.045129   
3  0.001106 -100.000000    0.016188    0.024491    0.031148    0.038100   
4  0.000838 -100.000000 -100.000000 -100.000000 -100.000000 -100.000000   
5  0.000634    0.000479    0.000362    0.000260 -100.000000    0.119308   

           6         7          8           9         10        11  
0    0.075041  0.088677 -100.00000    0.715844  0.839574  1.000000  
1 -100.000000  0.104505 -100.00000    0.618614  0.612760 -1.000000  
2 -100.000000  0.123018 -100.00000    0.533977  0.519160  0.318092  
3 -100.000000  0.144747 -100.00000    0.465009  0.447474  0.381081  
4 -100.000000  0.170287 -100.00000 -100.000000  0.381890  0.336352  
5    0.165708  0.200325    0.23623    0.278016  0.327076  0.301047

In [ ]:
print(np.round(V, decimals=2))

[[ 0.0e+00  0.0e+00  0.0e+00  1.0e-02 -1.0e+02  6.0e-02  8.0e-02  9.0e-02
  -1.0e+02  7.2e-01  8.4e-01  1.0e+00]
 [ 0.0e+00  0.0e+00  1.0e-02  1.0e-02 -1.0e+02  5.0e-02 -1.0e+02  1.0e-01
  -1.0e+02  6.2e-01  6.1e-01 -1.0e+00]
 [ 0.0e+00 -1.0e+02 -1.0e+02  2.0e-02 -1.0e+02  5.0e-02 -1.0e+02  1.2e-01
  -1.0e+02  5.3e-01  5.2e-01  3.2e-01]
 [ 0.0e+00 -1.0e+02  2.0e-02  2.0e-02  3.0e-02  4.0e-02 -1.0e+02  1.4e-01
  -1.0e+02  4.7e-01  4.5e-01  3.8e-01]
 [ 0.0e+00 -1.0e+02 -1.0e+02 -1.0e+02 -1.0e+02 -1.0e+02 -1.0e+02  1.7e-01
  -1.0e+02 -1.0e+02  3.8e-01  3.4e-01]
 [ 0.0e+00  0.0e+00  0.0e+00  0.0e+00 -1.0e+02  1.2e-01  1.7e-01  2.0e-01
   2.4e-01  2.8e-01  3.3e-01  3.0e-01]]


In [ ]:
masked_data = np.ma.masked_where(np.round(V, decimals=3) == -100, np.round(V, decimals=6))

# Output
print(masked_data)

[[0.000812 0.002257 0.0048 0.008252 -- 0.063118 0.075041 0.088677 --
  0.715844 0.839574 1.0]
 [0.001919 0.004449 0.008221 0.013012 -- 0.053394 -- 0.104505 -- 0.618614
  0.61276 -1.0]
 [0.001458 -- -- 0.01853 -- 0.045129 -- 0.123018 -- 0.533977 0.51916
  0.318092]
 [0.001106 -- 0.016188 0.024491 0.031148 0.0381 -- 0.144747 -- 0.465009
  0.447474 0.381081]
 [0.000838 -- -- -- -- -- -- 0.170287 -- -- 0.38189 0.336352]
 [0.000634 0.000479 0.000362 0.00026 -- 0.119308 0.165708 0.200325
  0.23623 0.278016 0.327076 0.301047]]
